name: "damage-classification"
platform: "tensorflow_savedmodel"
max_batch_size: 0
input [
	{
		name: "input_1"
		data_type: TYPE_FP32
		dims: [-1, 128,128,3]
	}
]
output [
	{
		name: "dense_3"
		data_type: TYPE_FP32
		dims: [-1, 4]
	}
]
