version: "3.5"

services:

  triton:
    image: 'nvcr.io/nvidia/tritonserver:22.06-py3'
    env_file: .aws.env
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
    command:
      [
        'tritonserver',
        '--model-repository=s3://sarah-majors/models/'
      ]

  main:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: /home/ec2-user/xView2_baseline
        target: /working_dir
    ports:
      - "8005:8005"
    depends_on:
      - triton
      - damage-classification

  damage-classification:
    build:
      context: ./model
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: /home/ec2-user/xView2_baseline
        target: /working_dir
    ports:
      - "8004:8004"
    depends_on:
      - triton
